version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2013
clone_depth: 1
build_script:
- cmd: >-
    build.bat
test: off
artifacts:
- path: win_hws2xml.zip
- path: mono_hws2xml.zip
